# Generated by Django 6.1.1 on 2026-10-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='semestergpa',
            name='semester',
            field=models.CharField(choices=[('HARMATTAN', 'Harmattan'), ('RAIN', 'Rain')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(100, '100'), (200, '200'), (300, '300'), (400, '400'), (500, '500'), (600, '600')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='matric_number',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AddConstraint(
            model_name='guardian',
            constraint=models.UniqueConstraint(fields=('student', 'email'), name='one_guardian_email_per_student'),
        ),
        migrations.AddConstraint(
            model_name='studentfile',
            constraint=models.UniqueConstraint(fields=('student', 'file_type', 'cloud_url'), name='one_file_link_per_student_and_type'),
        ),
    ]
