# Generated by Django 6.1.1 on 2026-10-04 09:51

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_student_must_change_password_student_surname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_session', models.CharField(max_length=9)),
                ('current_semester', models.CharField(choices=[('HARMATTAN', 'Harmattan'), ('RAIN', 'Rain')], default='HARMATTAN', max_length=10)),
                ('registration_open', models.BooleanField(default=False)),
                ('min_units', models.PositiveSmallIntegerField(default=0)),
                ('max_units', models.PositiveSmallIntegerField(default=0)),
                ('warning_gpa', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=3)),
                ('watch_gpa', models.DecimalField(decimal_places=2, default=Decimal('2.25'), max_digits=3)),
            ],
            options={
                'verbose_name_plural': 'academic calendar',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(100, '100'), (200, '200'), (300, '300'), (400, '400'), (500, '500')], default=100),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='required_for', to='portal.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('HARMATTAN', 'Harmattan'), ('RAIN', 'Rain')], default='HARMATTAN', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(100, '100'), (200, '200'), (300, '300'), (400, '400'), (500, '500')]),
        ),
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=9)),
                ('semester', models.CharField(choices=[('HARMATTAN', 'Harmattan'), ('RAIN', 'Rain')], max_length=10)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='portal.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='portal.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'course', 'session'), name='one_registration_per_course_session')],
            },
        ),
    ]
