"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

import os
import dotenv

dotenv.load_dotenv() # This loads variables from your .env file

SECRET_KEY = os.getenv('SECRET_KEY')
DEBUG = os.getenv('DEBUG', 'False') == 'True'


# Apply these strict security settings ONLY when DEBUG is False (Production)


ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'portal'
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "portal.middleware.ForcePasswordChangeMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    "default": {                                        # "default" = the main database
        "ENGINE": "django.db.backends.postgresql",      # use PostgreSQL (not the default SQLite)
        "NAME": "results_db",                           # the database you created in pgAdmin
        "USER": "postgres",                             # the PostgreSQL user
        "PASSWORD": "bilal",           # the password you set at install
        "HOST": "localhost",                            # database is on this same computer
        "PORT": "5432",                                 # PostgreSQL's default port
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

# Use MAILERS exclusively instead of mixing top-level EMAIL_BACKEND variables
MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    }
}

# If you want to use SMTP when deploying (DEBUG = False), configure it inside MAILERS:
if not DEBUG:
    MAILERS = {
        'default': {
            'BACKEND': 'django.core.mail.backends.smtp.EmailBackend',
            'HOST': 'your-smtp-server.com',
            'PORT': 587,
            'HOST_USER': 'your-email@domain.com',
            'HOST_PASSWORD': 'your-email-password',
            'USE_TLS': True,
        }
    }

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",    # normal username + password login
    "portal.auth_backends.FirstLoginBackend",       # a student's first login with their surname
]
LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "login"

if not DEBUG:
    SECURE_HSTS_SECONDS = 31536000  # Forces browsers to use HTTPS for 1 year (W004)
    SECURE_SSL_REDIRECT = True       # Redirects all HTTP traffic to HTTPS (W008)
    SESSION_COOKIE_SECURE = True     # Ensures session cookies are only sent over HTTPS (W012)
    CSRF_COOKIE_SECURE = True        # Ensures CSRF tokens are only sent over HTTPS (W016)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True  # Applies HSTS to all subdomains (W022)
    SECURE_HSTS_PRELOAD = True           # Allows your site to be included in browsers' HSTS preload list (W024)